# =============================================================
# MojRok — Phase 1 Setup Script
# Target: C:\Users\APIS\OneDrive\Desktop\MojRok
# Requires: .NET SDK 9.0.x, dotnet-ef 9.0.7 (global tool)
# Compatible: Windows PowerShell 5.1+ and PowerShell 7+
#
# SAFETY RULES:
#   - Run from a CLEAN, EMPTY MojRok folder.
#   - Script will STOP if MojRok.sln already exists.
#   - dotnet new --force only overwrites generated template files.
#   - No real DB credentials are written anywhere.
#   - `dotnet ef database update` is NOT run.
# =============================================================

Set-StrictMode -Version Latest
# Note: $ErrorActionPreference = Stop catches PowerShell cmdlet errors.
# External process (dotnet) failures are NOT caught — check output manually.
$ErrorActionPreference = 'Stop'

function Write-Step  { param($msg) Write-Host "`n>>> $msg" -ForegroundColor Cyan }
function Write-Done  { param($msg) Write-Host "    [OK] $msg" -ForegroundColor Green }
function Write-Warn  { param($msg) Write-Host "    [WARN] $msg" -ForegroundColor Yellow }
function Write-Fatal {
    param($msg)
    Write-Host "`n[FATAL] $msg" -ForegroundColor Red
    exit 1
}

# -----------------------------------------------------------
# GUARD — require a clean folder before doing anything
# -----------------------------------------------------------
if (Test-Path 'MojRok.sln') {
    Write-Fatal (
        "MojRok.sln already exists.`n" +
        "Delete all generated content and re-run from a clean folder.`n" +
        "Only delete files YOU know were generated by this script."
    )
}

Write-Host "`n=== MojRok Phase 1 Setup ===" -ForegroundColor Yellow
Write-Host "    Directory : $(Get-Location)"
Write-Host "    PowerShell: $($PSVersionTable.PSVersion)"

# -----------------------------------------------------------
# HELPER — write a UTF-8 file, creating parent dirs as needed
# Note: Set-Content -Encoding UTF8 writes UTF-8 with BOM on PS 5.1.
# This is safe for .NET 9 tooling and Visual Studio 2022.
# -----------------------------------------------------------
function Write-File {
    param([string]$Path, [string]$Content)
    $dir = Split-Path -Path $Path -Parent
    if ($dir -and -not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
    Set-Content -Path $Path -Value $Content -Encoding UTF8
    Write-Done "  $Path"
}

# -----------------------------------------------------------
# STEP 1 — Solution and projects
# -----------------------------------------------------------
Write-Step 'STEP 1 — Solution and projects'

dotnet new sln -n MojRok
dotnet new gitignore --force

# --force only overwrites the template-generated files inside each project folder.
# It will NOT delete any files you placed there manually.
dotnet new classlib   -n MojRok.Domain         -o src/MojRok.Domain         -f net9.0 --force
dotnet new classlib   -n MojRok.Application    -o src/MojRok.Application    -f net9.0 --force
dotnet new classlib   -n MojRok.Infrastructure -o src/MojRok.Infrastructure  -f net9.0 --force
dotnet new webapi     -n MojRok.API            -o src/MojRok.API            -f net9.0 --force
dotnet new blazorwasm -n MojRok.Client         -o src/MojRok.Client         -f net9.0 --force
dotnet new xunit      -n MojRok.Tests          -o tests/MojRok.Tests        -f net9.0 --force

dotnet sln add src/MojRok.Domain/MojRok.Domain.csproj
dotnet sln add src/MojRok.Application/MojRok.Application.csproj
dotnet sln add src/MojRok.Infrastructure/MojRok.Infrastructure.csproj
dotnet sln add src/MojRok.API/MojRok.API.csproj
dotnet sln add src/MojRok.Client/MojRok.Client.csproj
dotnet sln add tests/MojRok.Tests/MojRok.Tests.csproj

Write-Done 'Solution and 6 projects created'

# -----------------------------------------------------------
# STEP 2 — Project references
# Enforces the dependency direction:
#   Domain <- Application <- Infrastructure <- API
#   Tests  <- Domain + Application
#   Client is standalone (no project references)
# -----------------------------------------------------------
Write-Step 'STEP 2 — Project references'

dotnet add src/MojRok.Application    reference src/MojRok.Domain
dotnet add src/MojRok.Infrastructure reference src/MojRok.Application
dotnet add src/MojRok.Infrastructure reference src/MojRok.Domain
dotnet add src/MojRok.API            reference src/MojRok.Application
dotnet add src/MojRok.API            reference src/MojRok.Infrastructure
dotnet add tests/MojRok.Tests        reference src/MojRok.Domain
dotnet add tests/MojRok.Tests        reference src/MojRok.Application

Write-Done 'Project references set'

# -----------------------------------------------------------
# STEP 3 — Delete generated placeholder and demo files
# Only deletes files that dotnet templates generate by default.
# -----------------------------------------------------------
Write-Step 'STEP 3 — Removing generated placeholder and demo files'

$filesToDelete = @(
    # classlib placeholder
    'src/MojRok.Domain/Class1.cs',
    'src/MojRok.Application/Class1.cs',
    'src/MojRok.Infrastructure/Class1.cs',
    # webapi minimal-API weather example (may be inline in Program.cs — handled in Step 8)
    'src/MojRok.API/WeatherForecast.cs',
    # xunit placeholder
    'tests/MojRok.Tests/UnitTest1.cs',
    # Blazor WASM demo pages — not part of Phase 1
    'src/MojRok.Client/Pages/Counter.razor',
    'src/MojRok.Client/Pages/Counter.razor.css',
    'src/MojRok.Client/Pages/Weather.razor',
    'src/MojRok.Client/Pages/Weather.razor.css'
)

foreach ($f in $filesToDelete) {
    if (Test-Path $f) {
        Remove-Item $f -Force
        Write-Done "Deleted $f"
    }
}

# -----------------------------------------------------------
# STEP 4 — Write final .csproj files
#
# Package versions:
#   Microsoft.EntityFrameworkCore          9.0.7
#   Microsoft.EntityFrameworkCore.Design   9.0.7
#   Npgsql.EntityFrameworkCore.PostgreSQL  9.0.7
#   Swashbuckle.AspNetCore                 7.3.1
#
# If `dotnet restore` fails for Npgsql 9.0.7 (not yet released),
# change the Npgsql version to 9.0.4 in MojRok.Infrastructure.csproj.
# Any 9.x Npgsql release is compatible with EF Core 9.x.
#
# Microsoft.EntityFrameworkCore.Design is marked PrivateAssets=all
# so it is a build-time-only dependency and does not leak into consumers.
# It is added to both Infrastructure (migration assembly) and API
# (--startup-project for `dotnet ef` tooling).
# -----------------------------------------------------------
Write-Step 'STEP 4 — Writing .csproj files'

Set-Content -Path 'src/MojRok.Domain/MojRok.Domain.csproj' -Encoding UTF8 -Value @'
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>
'@
Write-Done 'MojRok.Domain.csproj'

Set-Content -Path 'src/MojRok.Application/MojRok.Application.csproj' -Encoding UTF8 -Value @'
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <!--
      Application references EF Core abstractions (DbSet<T>) for IAppDbContext.
      It never references Npgsql or the concrete AppDbContext — only Infrastructure does.
    -->
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.7" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MojRok.Domain\MojRok.Domain.csproj" />
  </ItemGroup>
</Project>
'@
Write-Done 'MojRok.Application.csproj'

Set-Content -Path 'src/MojRok.Infrastructure/MojRok.Infrastructure.csproj' -Encoding UTF8 -Value @'
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <!--
      Design package: required for `dotnet ef migrations add` targeting this project.
      PrivateAssets=all prevents it from leaking into MojRok.API at runtime.
    -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  <Publish>true</Publish>
    </PackageReference>
    <!--
      Npgsql EF Core provider. Any 9.x version is compatible with EF Core 9.x.
      If 9.0.7 is unavailable on NuGet, change to 9.0.4.
    -->
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.7" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MojRok.Application\MojRok.Application.csproj" />
    <ProjectReference Include="..\MojRok.Domain\MojRok.Domain.csproj" />
  </ItemGroup>
</Project>
'@
Write-Done 'MojRok.Infrastructure.csproj'

Set-Content -Path 'src/MojRok.API/MojRok.API.csproj' -Encoding UTF8 -Value @'
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  <Publish>true</Publish>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MojRok.Application\MojRok.Application.csproj" />
    <ProjectReference Include="..\MojRok.Infrastructure\MojRok.Infrastructure.csproj" />
  </ItemGroup>
</Project>
'@
Write-Done 'MojRok.API.csproj'

Set-Content -Path 'src/MojRok.Client/MojRok.Client.csproj' -Encoding UTF8 -Value @'
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.7" PrivateAssets="all" />
  </ItemGroup>
  <!--
    Client is standalone — no project references to Domain, Application, or Infrastructure.
    It communicates with MojRok.API exclusively over HTTP.
    HttpClient base address will be configured in Phase 9.
  -->
</Project>
'@
Write-Done 'MojRok.Client.csproj'

Set-Content -Path 'tests/MojRok.Tests/MojRok.Tests.csproj' -Encoding UTF8 -Value @'
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk"    Version="17.12.0" />
    <PackageReference Include="xunit"                     Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector"        Version="6.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <!--
      Tests reference Domain and Application only.
      Infrastructure is never referenced from tests directly.
    -->
    <ProjectReference Include="..\..\src\MojRok.Domain\MojRok.Domain.csproj" />
    <ProjectReference Include="..\..\src\MojRok.Application\MojRok.Application.csproj" />
  </ItemGroup>
</Project>
'@
Write-Done 'MojRok.Tests.csproj'

# -----------------------------------------------------------
# STEP 5 — Domain layer: Enums + Entities
# -----------------------------------------------------------
Write-Step 'STEP 5 — Domain layer'

Write-File 'src/MojRok.Domain/Enums/UserRole.cs' @'
namespace MojRok.Domain.Enums;

public enum UserRole
{
    Citizen,
    Admin
}
'@

Write-File 'src/MojRok.Domain/Enums/DeadlineStatus.cs' @'
namespace MojRok.Domain.Enums;

public enum DeadlineStatus
{
    Active,
    Upcoming,
    Urgent,
    Expired,
    Completed
}
'@

Write-File 'src/MojRok.Domain/Enums/ReminderChannel.cs' @'
namespace MojRok.Domain.Enums;

public enum ReminderChannel
{
    InApp,
    Email
}
'@

Write-File 'src/MojRok.Domain/Entities/Municipality.cs' @'
namespace MojRok.Domain.Entities;

public class Municipality
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string NameMk { get; set; } = string.Empty;
    public string Region { get; set; } = string.Empty;

    // Navigation
    public ICollection<AppUser> Users { get; set; } = [];
    public ICollection<CitizenService> CitizenServices { get; set; } = [];
}
'@

Write-File 'src/MojRok.Domain/Entities/AppUser.cs' @'
using MojRok.Domain.Enums;

namespace MojRok.Domain.Entities;

public class AppUser
{
    public Guid Id { get; set; }
    public string Email { get; set; } = string.Empty;
    public string PasswordHash { get; set; } = string.Empty;
    public string FullName { get; set; } = string.Empty;
    public string? PhoneNumber { get; set; }
    public int? MunicipalityId { get; set; }
    public string PreferredLanguage { get; set; } = "mk";
    public UserRole Role { get; set; } = UserRole.Citizen;
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public bool IsActive { get; set; } = true;

    // Navigation
    public Municipality? Municipality { get; set; }
    public ICollection<Deadline> Deadlines { get; set; } = [];
    public ICollection<Category> Categories { get; set; } = [];
    public ICollection<Reminder> Reminders { get; set; } = [];
}
'@

Write-File 'src/MojRok.Domain/Entities/Category.cs' @'
namespace MojRok.Domain.Entities;

public class Category
{
    public Guid Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Color { get; set; } = "#6366F1";
    public string? IconSlug { get; set; }

    // Nullable: null = system/default category not owned by any specific user.
    // User-created categories have a non-null UserId.
    public Guid? UserId { get; set; }
    public bool IsDefault { get; set; } = false;

    // Navigation
    public AppUser? User { get; set; }
    public ICollection<Deadline> Deadlines { get; set; } = [];
}
'@

Write-File 'src/MojRok.Domain/Entities/Deadline.cs' @'
using MojRok.Domain.Enums;

namespace MojRok.Domain.Entities;

public class Deadline
{
    public Guid Id { get; set; }
    public string Title { get; set; } = string.Empty;
    public string? Description { get; set; }
    public DateTime DueDate { get; set; }
    public Guid UserId { get; set; }
    public Guid CategoryId { get; set; }
    public bool IsRecurring { get; set; } = false;
    public int? RecurrenceIntervalDays { get; set; }
    public bool IsCompleted { get; set; } = false;
    public DateTime? CompletedAt { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    // Navigation
    public AppUser User { get; set; } = null!;
    public Category Category { get; set; } = null!;
    public ICollection<Reminder> Reminders { get; set; } = [];

    /// <summary>
    /// Computed from DueDate at runtime. Never stored in the database.
    /// EF Core configuration calls builder.Ignore(d => d.Status).
    /// Priority: Completed > Expired > Urgent > Upcoming > Active.
    /// </summary>
    public DeadlineStatus Status
    {
        get
        {
            if (IsCompleted) return DeadlineStatus.Completed;

            var today = DateTime.UtcNow.Date;
            var due   = DueDate.Date;

            if (due < today)              return DeadlineStatus.Expired;
            if (due <= today.AddDays(3))  return DeadlineStatus.Urgent;
            if (due <= today.AddDays(14)) return DeadlineStatus.Upcoming;

            return DeadlineStatus.Active;
        }
    }
}
'@

Write-File 'src/MojRok.Domain/Entities/Reminder.cs' @'
using MojRok.Domain.Enums;

namespace MojRok.Domain.Entities;

public class Reminder
{
    public Guid Id { get; set; }
    public Guid DeadlineId { get; set; }
    public Guid UserId { get; set; }
    public DateTime ReminderDate { get; set; }
    public ReminderChannel Channel { get; set; } = ReminderChannel.InApp;
    public bool IsSent { get; set; } = false;
    public DateTime? SentAt { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    // Navigation
    public Deadline Deadline { get; set; } = null!;
    public AppUser User { get; set; } = null!;
}
'@

Write-File 'src/MojRok.Domain/Entities/ServiceCategory.cs' @'
namespace MojRok.Domain.Entities;

public class ServiceCategory
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string NameMk { get; set; } = string.Empty;
    public string? IconSlug { get; set; }
    public int SortOrder { get; set; }

    // Navigation
    public ICollection<CitizenService> CitizenServices { get; set; } = [];
}
'@

Write-File 'src/MojRok.Domain/Entities/CitizenService.cs' @'
namespace MojRok.Domain.Entities;

public class CitizenService
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string NameMk { get; set; } = string.Empty;
    public string? Description { get; set; }
    public string? DescriptionMk { get; set; }
    public int ServiceCategoryId { get; set; }
    public int? MunicipalityId { get; set; }
    public string WebsiteUrl { get; set; } = string.Empty;
    public string? PhoneNumber { get; set; }
    public bool IsActive { get; set; } = true;

    // Navigation
    public ServiceCategory ServiceCategory { get; set; } = null!;
    public Municipality? Municipality { get; set; }
}
'@

Write-Done 'Domain layer complete'

# -----------------------------------------------------------
# STEP 6 — Application layer
# -----------------------------------------------------------
Write-Step 'STEP 6 — Application layer'

Write-File 'src/MojRok.Application/Abstractions/IAppDbContext.cs' @'
using Microsoft.EntityFrameworkCore;
using MojRok.Domain.Entities;

namespace MojRok.Application.Abstractions;

/// <summary>
/// Abstraction over AppDbContext used by Application service classes.
/// Keeps Application layer independent of Npgsql and the concrete context.
/// Infrastructure implements this interface; Application never references it directly.
/// </summary>
public interface IAppDbContext
{
    DbSet<AppUser>         Users             { get; }
    DbSet<Municipality>    Municipalities    { get; }
    DbSet<Category>        Categories        { get; }
    DbSet<Deadline>        Deadlines         { get; }
    DbSet<Reminder>        Reminders         { get; }
    DbSet<ServiceCategory> ServiceCategories { get; }
    DbSet<CitizenService>  CitizenServices   { get; }

    Task<int> SaveChangesAsync(CancellationToken cancellationToken = default);
}
'@

Write-Done 'Application layer complete'

# -----------------------------------------------------------
# STEP 7 — Infrastructure layer
# -----------------------------------------------------------
Write-Step 'STEP 7 — Infrastructure layer'

Write-File 'src/MojRok.Infrastructure/Persistence/AppDbContext.cs' @'
using Microsoft.EntityFrameworkCore;
using MojRok.Application.Abstractions;
using MojRok.Domain.Entities;

namespace MojRok.Infrastructure.Persistence;

public class AppDbContext : DbContext, IAppDbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) { }

    public DbSet<AppUser>         Users             => Set<AppUser>();
    public DbSet<Municipality>    Municipalities    => Set<Municipality>();
    public DbSet<Category>        Categories        => Set<Category>();
    public DbSet<Deadline>        Deadlines         => Set<Deadline>();
    public DbSet<Reminder>        Reminders         => Set<Reminder>();
    public DbSet<ServiceCategory> ServiceCategories => Set<ServiceCategory>();
    public DbSet<CitizenService>  CitizenServices   => Set<CitizenService>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // Scans this assembly for all IEntityTypeConfiguration<T> classes
        // and applies them automatically.
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(AppDbContext).Assembly);
        base.OnModelCreating(modelBuilder);
    }
}
'@

Write-File 'src/MojRok.Infrastructure/Persistence/Configurations/AppUserConfiguration.cs' @'
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MojRok.Domain.Entities;

namespace MojRok.Infrastructure.Persistence.Configurations;

public class AppUserConfiguration : IEntityTypeConfiguration<AppUser>
{
    public void Configure(EntityTypeBuilder<AppUser> builder)
    {
        builder.HasKey(u => u.Id);

        builder.Property(u => u.Email)
            .IsRequired()
            .HasMaxLength(256);

        builder.HasIndex(u => u.Email)
            .IsUnique();

        builder.Property(u => u.PasswordHash)
            .IsRequired();

        builder.Property(u => u.FullName)
            .IsRequired()
            .HasMaxLength(200);

        builder.Property(u => u.PhoneNumber)
            .HasMaxLength(20);

        builder.Property(u => u.PreferredLanguage)
            .IsRequired()
            .HasMaxLength(2)
            .HasDefaultValue("mk");

        builder.Property(u => u.Role)
            .HasConversion<string>()
            .HasMaxLength(20);

        // MunicipalityId is nullable: a user may not belong to any municipality.
        // SetNull: deleting a municipality clears user.MunicipalityId, never deletes the user.
        builder.HasOne(u => u.Municipality)
            .WithMany(m => m.Users)
            .HasForeignKey(u => u.MunicipalityId)
            .OnDelete(DeleteBehavior.SetNull);
    }
}
'@

Write-File 'src/MojRok.Infrastructure/Persistence/Configurations/MunicipalityConfiguration.cs' @'
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MojRok.Domain.Entities;

namespace MojRok.Infrastructure.Persistence.Configurations;

public class MunicipalityConfiguration : IEntityTypeConfiguration<Municipality>
{
    public void Configure(EntityTypeBuilder<Municipality> builder)
    {
        builder.HasKey(m => m.Id);

        builder.Property(m => m.Name)
            .IsRequired()
            .HasMaxLength(100);

        builder.Property(m => m.NameMk)
            .IsRequired()
            .HasMaxLength(100);

        builder.Property(m => m.Region)
            .IsRequired()
            .HasMaxLength(100);
    }
}
'@

Write-File 'src/MojRok.Infrastructure/Persistence/Configurations/CategoryConfiguration.cs' @'
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MojRok.Domain.Entities;

namespace MojRok.Infrastructure.Persistence.Configurations;

public class CategoryConfiguration : IEntityTypeConfiguration<Category>
{
    public void Configure(EntityTypeBuilder<Category> builder)
    {
        builder.HasKey(c => c.Id);

        builder.Property(c => c.Name)
            .IsRequired()
            .HasMaxLength(100);

        builder.Property(c => c.Color)
            .IsRequired()
            .HasMaxLength(7)
            .HasDefaultValue("#6366F1");

        builder.Property(c => c.IconSlug)
            .HasMaxLength(50);

        // UserId is NULLABLE (Guid?).
        // null  = system/default category visible to all users.
        // value = personal category belonging to a specific user.
        // IsRequired(false) explicitly maps the nullable FK column.
        // Cascade: deleting a user removes their personal categories.
        //          System categories (UserId = null) are not affected.
        builder.HasOne(c => c.User)
            .WithMany(u => u.Categories)
            .HasForeignKey(c => c.UserId)
            .IsRequired(false)
            .OnDelete(DeleteBehavior.Cascade);
    }
}
'@

Write-File 'src/MojRok.Infrastructure/Persistence/Configurations/DeadlineConfiguration.cs' @'
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MojRok.Domain.Entities;

namespace MojRok.Infrastructure.Persistence.Configurations;

public class DeadlineConfiguration : IEntityTypeConfiguration<Deadline>
{
    public void Configure(EntityTypeBuilder<Deadline> builder)
    {
        builder.HasKey(d => d.Id);

        builder.Property(d => d.Title)
            .IsRequired()
            .HasMaxLength(200);

        builder.Property(d => d.Description)
            .HasMaxLength(1000);

        builder.Property(d => d.DueDate)
            .IsRequired();

        // Status is computed from DueDate at runtime. Never stored in the DB.
        builder.Ignore(d => d.Status);

        // Composite indexes to support the most common queries:
        //   - All deadlines for a user
        //   - Filter/sort by due date per user
        //   - Filter by completion state per user
        builder.HasIndex(d => d.UserId);
        builder.HasIndex(d => new { d.UserId, d.DueDate });
        builder.HasIndex(d => new { d.UserId, d.IsCompleted });

        // Cascade: deleting a user removes all their deadlines.
        builder.HasOne(d => d.User)
            .WithMany(u => u.Deadlines)
            .HasForeignKey(d => d.UserId)
            .OnDelete(DeleteBehavior.Cascade);

        // Restrict: prevents deleting a Category that still has Deadlines.
        // The API must enforce category change/re-assignment before deletion.
        builder.HasOne(d => d.Category)
            .WithMany(c => c.Deadlines)
            .HasForeignKey(d => d.CategoryId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
'@

Write-File 'src/MojRok.Infrastructure/Persistence/Configurations/ReminderConfiguration.cs' @'
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MojRok.Domain.Entities;

namespace MojRok.Infrastructure.Persistence.Configurations;

public class ReminderConfiguration : IEntityTypeConfiguration<Reminder>
{
    public void Configure(EntityTypeBuilder<Reminder> builder)
    {
        builder.HasKey(r => r.Id);

        builder.Property(r => r.ReminderDate)
            .IsRequired();

        builder.Property(r => r.Channel)
            .HasConversion<string>()
            .HasMaxLength(20);

        // BackgroundService query: find all unsent reminders due on or before today.
        builder.HasIndex(r => new { r.IsSent, r.ReminderDate });

        // Cascade: deleting a Deadline removes all its Reminders.
        builder.HasOne(r => r.Deadline)
            .WithMany(d => d.Reminders)
            .HasForeignKey(r => r.DeadlineId)
            .OnDelete(DeleteBehavior.Cascade);

        // NoAction on Reminder -> User FK.
        // When a User is deleted the cascade chain is:
        //   User (deleted) -> Deadlines (Cascade) -> Reminders (Cascade via DeadlineId)
        // Reminders are gone before PostgreSQL re-checks reminder.UserId.
        // A second Cascade from Reminder -> User would create multiple cascade
        // paths on the same table, which PostgreSQL rejects with a migration error.
        builder.HasOne(r => r.User)
            .WithMany(u => u.Reminders)
            .HasForeignKey(r => r.UserId)
            .OnDelete(DeleteBehavior.NoAction);
    }
}
'@

Write-File 'src/MojRok.Infrastructure/Persistence/Configurations/ServiceCategoryConfiguration.cs' @'
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MojRok.Domain.Entities;

namespace MojRok.Infrastructure.Persistence.Configurations;

public class ServiceCategoryConfiguration : IEntityTypeConfiguration<ServiceCategory>
{
    public void Configure(EntityTypeBuilder<ServiceCategory> builder)
    {
        builder.HasKey(sc => sc.Id);

        builder.Property(sc => sc.Name)
            .IsRequired()
            .HasMaxLength(100);

        builder.Property(sc => sc.NameMk)
            .IsRequired()
            .HasMaxLength(100);

        builder.Property(sc => sc.IconSlug)
            .HasMaxLength(50);
    }
}
'@

Write-File 'src/MojRok.Infrastructure/Persistence/Configurations/CitizenServiceConfiguration.cs' @'
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MojRok.Domain.Entities;

namespace MojRok.Infrastructure.Persistence.Configurations;

public class CitizenServiceConfiguration : IEntityTypeConfiguration<CitizenService>
{
    public void Configure(EntityTypeBuilder<CitizenService> builder)
    {
        builder.HasKey(cs => cs.Id);

        builder.Property(cs => cs.Name)
            .IsRequired()
            .HasMaxLength(200);

        builder.Property(cs => cs.NameMk)
            .IsRequired()
            .HasMaxLength(200);

        builder.Property(cs => cs.Description)
            .HasMaxLength(1000);

        builder.Property(cs => cs.DescriptionMk)
            .HasMaxLength(1000);

        builder.Property(cs => cs.WebsiteUrl)
            .IsRequired()
            .HasMaxLength(500);

        builder.Property(cs => cs.PhoneNumber)
            .HasMaxLength(20);

        builder.HasIndex(cs => cs.ServiceCategoryId);
        builder.HasIndex(cs => cs.IsActive);

        // Restrict: prevents deleting a ServiceCategory that still has services.
        builder.HasOne(cs => cs.ServiceCategory)
            .WithMany(sc => sc.CitizenServices)
            .HasForeignKey(cs => cs.ServiceCategoryId)
            .OnDelete(DeleteBehavior.Restrict);

        // MunicipalityId nullable: null means the service is national (not city-specific).
        // SetNull: deleting a municipality clears the FK, keeps the service record.
        builder.HasOne(cs => cs.Municipality)
            .WithMany(m => m.CitizenServices)
            .HasForeignKey(cs => cs.MunicipalityId)
            .IsRequired(false)
            .OnDelete(DeleteBehavior.SetNull);
    }
}
'@

Write-File 'src/MojRok.Infrastructure/Extensions/InfrastructureServiceExtensions.cs' @'
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using MojRok.Application.Abstractions;
using MojRok.Infrastructure.Persistence;

namespace MojRok.Infrastructure.Extensions;

public static class InfrastructureServiceExtensions
{
    public static IServiceCollection AddInfrastructure(
        this IServiceCollection services,
        IConfiguration configuration)
    {
        var connectionString = configuration.GetConnectionString("DefaultConnection")
            ?? throw new InvalidOperationException(
                "Connection string 'DefaultConnection' is not configured. " +
                "Use `dotnet user-secrets` for local development " +
                "and environment variables in production.");

        services.AddDbContext<AppDbContext>(options =>
            options.UseNpgsql(connectionString));

        // Register as IAppDbContext so Application services never depend on
        // the concrete class or Npgsql directly.
        services.AddScoped<IAppDbContext>(sp =>
            sp.GetRequiredService<AppDbContext>());

        return services;
    }
}
'@

Write-Done 'Infrastructure layer complete'

# -----------------------------------------------------------
# STEP 8 — API layer
# -----------------------------------------------------------
Write-Step 'STEP 8 — API layer'

# Replaces the dotnet new webapi generated Program.cs (which uses minimal APIs
# and contains the WeatherForecast example). We use controller-based routing
# because controllers will be added in Phase 2.
Write-File 'src/MojRok.API/Program.cs' @'
using MojRok.Infrastructure.Extensions;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddInfrastructure(builder.Configuration);

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();
app.UseAuthorization();
app.MapControllers();

app.Run();
'@

# Production appsettings: connection string intentionally empty.
# Credentials must NEVER be committed. Use user-secrets for local dev.
Write-File 'src/MojRok.API/appsettings.json' @'
{
  "ConnectionStrings": {
    "DefaultConnection": ""
  },
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*"
}
'@

# Local development placeholder — safe to commit (points at local Postgres only).
# For Supabase, use user-secrets instead (see post-script instructions).
Write-File 'src/MojRok.API/appsettings.Development.json' @'
{
  "ConnectionStrings": {
    "DefaultConnection": "Host=localhost;Database=mojrok_dev;Username=postgres;Password=<YOUR_LOCAL_PASSWORD>"
  }
}
'@

Write-Done 'API layer complete'

# -----------------------------------------------------------
# STEP 9 — Blazor Client minimal shell
# Replaces demo content. Keeps all scaffold files needed for routing
# (App.razor, Routes.razor, _Imports.razor, MainLayout.razor).
# Only demo pages (Counter, Weather) and their nav links are removed.
# -----------------------------------------------------------
Write-Step 'STEP 9 — Blazor Client minimal shell'

Write-File 'src/MojRok.Client/Program.cs' @'
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using MojRok.Client;

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");

// HttpClient base address points at the hosting origin during development.
// Phase 9 will configure this to point at the MojRok.API URL.
builder.Services.AddScoped(sp =>
    new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });

await builder.Build().RunAsync();
'@

Write-File 'src/MojRok.Client/Pages/Home.razor' @'
@page "/"

<PageTitle>MojRok</PageTitle>

<h1>MojRok 🇲🇰</h1>
<p>Платформа за рокови и потсетници / Citizen Deadline &amp; Reminder Platform.</p>
<p>UI implementation starts in Phase 9.</p>
'@

# Minimal NavMenu — Home link only. Counter and Weather links removed.
# MainLayout.razor retains its NavMenu reference and does not need changes.
Write-File 'src/MojRok.Client/Layout/NavMenu.razor' @'
<div class="top-row ps-3 navbar navbar-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="">MojRok</a>
    </div>
</div>

<input type="checkbox" title="Navigation menu" class="navbar-toggler" />

<div class="nav-scrollable" onclick="document.querySelector('.navbar-toggler').click()">
    <nav class="flex-column">
        <div class="nav-item px-3">
            <NavLink class="nav-link" href="" Match="NavLinkMatch.All">
                Home
            </NavLink>
        </div>
    </nav>
</div>
'@

Write-Done 'Blazor Client minimal shell complete'

# -----------------------------------------------------------
# STEP 10 — Tests
# -----------------------------------------------------------
Write-Step 'STEP 10 — Tests'

Write-File 'tests/MojRok.Tests/Domain/DeadlineStatusTests.cs' @'
using MojRok.Domain.Entities;
using MojRok.Domain.Enums;

namespace MojRok.Tests.Domain;

/// <summary>
/// Unit tests for the Deadline.Status computed property.
/// Status derives from DueDate at runtime and is never stored in the database.
///
/// Date/time note: tests use DateTime.UtcNow.AddDays(n). The Status getter
/// also calls DateTime.UtcNow.Date internally. The two calls are microseconds
/// apart so midnight-crossing flakiness is theoretical and acceptable for
/// domain-layer unit tests that do not use time injection.
/// </summary>
public class DeadlineStatusTests
{
    private static Deadline MakeDeadline(DateTime dueDate, bool isCompleted = false) => new()
    {
        Id          = Guid.NewGuid(),
        Title       = "Test Deadline",
        DueDate     = dueDate,
        IsCompleted = isCompleted,
        UserId      = Guid.NewGuid(),
        CategoryId  = Guid.NewGuid()
    };

    [Fact]
    public void Status_IsCompleted_WhenIsCompletedTrue()
    {
        // Completed takes priority over all date checks.
        var d = MakeDeadline(DateTime.UtcNow.AddDays(-1), isCompleted: true);
        Assert.Equal(DeadlineStatus.Completed, d.Status);
    }

    [Fact]
    public void Status_IsExpired_WhenDueDateYesterday()
    {
        var d = MakeDeadline(DateTime.UtcNow.AddDays(-1));
        Assert.Equal(DeadlineStatus.Expired, d.Status);
    }

    [Fact]
    public void Status_IsUrgent_WhenDueDateToday()
    {
        // due.Date == today.Date, so due < today is false, due <= today.AddDays(3) is true.
        var d = MakeDeadline(DateTime.UtcNow);
        Assert.Equal(DeadlineStatus.Urgent, d.Status);
    }

    [Fact]
    public void Status_IsUrgent_WhenDueDateIn3Days()
    {
        // Boundary: due.Date == today.AddDays(3) — still Urgent.
        var d = MakeDeadline(DateTime.UtcNow.AddDays(3));
        Assert.Equal(DeadlineStatus.Urgent, d.Status);
    }

    [Fact]
    public void Status_IsUpcoming_WhenDueDateIn4Days()
    {
        // Boundary: due.Date == today.AddDays(4) — first day of Upcoming.
        var d = MakeDeadline(DateTime.UtcNow.AddDays(4));
        Assert.Equal(DeadlineStatus.Upcoming, d.Status);
    }

    [Fact]
    public void Status_IsUpcoming_WhenDueDateIn14Days()
    {
        // Boundary: due.Date == today.AddDays(14) — last day of Upcoming.
        var d = MakeDeadline(DateTime.UtcNow.AddDays(14));
        Assert.Equal(DeadlineStatus.Upcoming, d.Status);
    }

    [Fact]
    public void Status_IsActive_WhenDueDateIn15Days()
    {
        // Boundary: due.Date == today.AddDays(15) — first day of Active.
        var d = MakeDeadline(DateTime.UtcNow.AddDays(15));
        Assert.Equal(DeadlineStatus.Active, d.Status);
    }

    [Fact]
    public void Status_IsActive_WhenDueDateFarFuture()
    {
        var d = MakeDeadline(DateTime.UtcNow.AddDays(90));
        Assert.Equal(DeadlineStatus.Active, d.Status);
    }

    [Fact]
    public void CompletedDeadline_IsNotExpired_EvenIfPastDue()
    {
        // A deadline marked complete 30 days past due must stay Completed, not Expired.
        var d = MakeDeadline(DateTime.UtcNow.AddDays(-30), isCompleted: true);
        Assert.NotEqual(DeadlineStatus.Expired, d.Status);
    }
}
'@

Write-Done 'Tests layer complete'

# -----------------------------------------------------------
# STEP 11 — dotnet restore, build, test
# -----------------------------------------------------------
Write-Step 'STEP 11 — dotnet restore'
dotnet restore
Write-Done 'Restore complete'

Write-Step 'STEP 11 — dotnet build --no-restore --configuration Release'
dotnet build --no-restore --configuration Release
Write-Done 'Build complete'

Write-Step 'STEP 11 — dotnet test --no-build --configuration Release'
dotnet test --no-build --configuration Release --verbosity normal
Write-Done 'Tests complete'

# -----------------------------------------------------------
# STEP 12 — EF Core InitialCreate migration
#
# Requires dotnet-ef 9.0.7 installed as a global tool.
# Install: dotnet tool install --global dotnet-ef --version "9.0.7"
#
# --project        : where migrations are generated (Infrastructure)
# --startup-project: provides the connection string + DI container (API)
# --output-dir     : relative to --project root
#
# `dotnet ef database update` is NOT run here.
# Run it manually only after you have a PostgreSQL instance ready.
# -----------------------------------------------------------
Write-Step 'STEP 12 — EF Core migration'

$efInstalled = dotnet tool list -g 2>&1 | Select-String 'dotnet-ef'
if (-not $efInstalled) {
    Write-Warn 'dotnet-ef global tool not found.'
    Write-Warn 'Install it with:'
    Write-Warn '  dotnet tool install --global dotnet-ef --version "9.0.7"'
    Write-Warn 'Then run the migration manually:'
    Write-Warn '  dotnet ef migrations add InitialCreate --project src/MojRok.Infrastructure --startup-project src/MojRok.API --output-dir Persistence/Migrations'
} else {
    Write-Done "dotnet-ef found: $efInstalled"

    dotnet ef migrations add InitialCreate `
        --project src/MojRok.Infrastructure `
        --startup-project src/MojRok.API `
        --output-dir Persistence/Migrations

    Write-Done 'Migration InitialCreate created in src/MojRok.Infrastructure/Persistence/Migrations/'
}

# -----------------------------------------------------------
Write-Host ''
Write-Host '=== Phase 1 Complete ===' -ForegroundColor Yellow
Write-Host ''
Write-Host 'Manual steps required after this script:' -ForegroundColor Cyan
Write-Host '  1. Configure Supabase connection string via user-secrets:'
Write-Host '       dotnet user-secrets init --project src/MojRok.API'
Write-Host '       dotnet user-secrets set "ConnectionStrings:DefaultConnection" "<your-supabase-url>" --project src/MojRok.API'
Write-Host '  2. When PostgreSQL is ready, apply the migration:'
Write-Host '       dotnet ef database update --project src/MojRok.Infrastructure --startup-project src/MojRok.API'
Write-Host '  3. Open MojRok.sln in Visual Studio 2022 and verify the solution loads cleanly.'
Write-Host ''

